### ISSUE TITLE
How to add a key shortcut to the menuitem?

### ISSUE THREAD

**Issue by ScruffyDerHausmeister** [csm101/EditInVsCodeDelphiPlugin#4]
How to add a key shortcut to the menuitem?

**Comment by csm101** [comment]
Hi, it already has a key shortcut (it's in my last commit, maybe you aren't using the latest sources).

It's CTRL+\

you can change it by editing this source line (check the last parameter):

```
TMenuHandler.AddMenuItem(NTAServices, 'Open in Visual Studio Code', OpenCurrentFileInVisualStudioCode, 'Ctrl+\');
```

it's at the end of the main unit.

**Comment by ScruffyDerHausmeister** [comment]
Thank you, I've got it. :-)
